spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: password122
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

api:
  security:
    ignored: /api/v1/students,/api/v1/newwwws,/api/v1/students/**,/swagger-ui/**,/v3/api-docs,/v3/api-docs/**